version: '3.3'

services:
    nginx:
        container_name: adm_nginx
        image: nginx:1.21.6-alpine
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        restart: always
        networks:
            - adm_network

    app:
        container_name: adm_app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        working_dir: /app
        restart: always
        volumes:
            - .:/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - adm_network

    database:
        container_name: database
        image: library/mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: cdmllove
            MYSQL_DATABASE: adm_db
        volumes:
            - data:/var/lib/mysql
            - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
        networks:
            - adm_network

    phpmyadmin:
        container_name: adm_phpmyadmin
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: cdmllove
        networks:
            - adm_network

volumes:
    data:
        driver: local

networks:
    adm_network:
        driver: bridge
